# -*- coding: utf-8 -*-
"""backend_new_approach.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kDzRBJGEWgeX-oV6gz-RjbZ7swIt_L8L
"""

#pip install sentence-transformers

# Importing libraries
import math
import http.client
import json
from sentence_transformers import SentenceTransformer, util
import pandas as pd
import numpy as np
import requests

def quote_pop(user_input):
  url = "https://raw.githubusercontent.com/JamesFT/Database-Quotes-JSON/master/quotes.json"
  resp = requests.get(url)
  data = json.loads(resp.text)
  print("Connection with database established")

  quotesList = []
  for i in range(len(data)):
    quotesList.append(data[i]["quoteText"])
  print("Quotes successfully retrieved")

  model = SentenceTransformer('all-mpnet-base-v2')
  print("Language model downloaded")

  # The sentences we'd like to encode
  # It's a hard-coded example for the sake of having a quick demo. 
  # Later on, this will be replaced directly by the user input.
  ourSentences = [user_input]

  # Get embeddings of sentences
  catEmbeddings = model.encode(quotesList)
  sentEmbeddings = model.encode(ourSentences)
  print("quotes and sentences embeddings done")

  quoteRes = [0]*len(catEmbeddings)
  maxSimRes = -math.inf

  # for each category
  for i in range(len(catEmbeddings)):
    # calculate the cosine similarity between our sentence embedding 
    # and the quote embedding
    currSimRes = util.cos_sim(sentEmbeddings, catEmbeddings[i]).item()
    # store the result in a results array
    quoteRes[i] = currSimRes
    # update the maxSimRes so it stores the highest similarity score
    maxSimRes = max(maxSimRes, currSimRes)
  print("Cosine similarity score calculated")


  # print("{0:.4f}".format(sim.tolist()[0][0])) 
  tempQuotes = sorted([*set(quoteRes)], reverse = True)
  print("quotes scores sorted")

  firstQ = tempQuotes[0]
  secondQ = tempQuotes[1]
  thirdQ = tempQuotes[2]
  

  # Retrieve the quote with the highest similarity score
  firsTargetQuote = quotesList[quoteRes.index(firstQ)]
  secondTargetQuote = quotesList[quoteRes.index(secondQ)]
  thirdTargetQuote = quotesList[quoteRes.index(thirdQ)]
  print("Target Quotes retrived")

  return [firsTargetQuote, secondTargetQuote, thirdTargetQuote]

quote_pop("I am so sorry you are going through a hard time. I wish I could be there for you. But don't worry, it will get better!")